baseURL = 'https://xpmephi.github.io/'
languageCode = 'ru'
title = 'XP MEPhI Wiki'
theme = 'book'

# Меню строится из дерева разделов в content/docs
[params]
  BookSection = 'docs'

[markup.goldmark.renderer]
  unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
